/**
 * @module seed.ts
 *
 * Database seeding script for local development and testing.
 *
 * This script initializes the database with:
 * 1. Default Family Members (Owners)
 * 2. Example Notebooks for each member
 * 3. Synthetic Source records to populate the UI grids
 *
 * Usage:
 * bun run seed.ts
 */
import { db } from "./src/db";
import { notebooks, owners, sources } from "./src/db/schema";

/**
 * Main seeding execution block.
 */
async function seed() {
  console.log("Seeding database...");

  // 1. Initial Family Members
  const ownersData = [
    { name: "PopPop" },
    { name: "MawMaw" },
    { name: "Emme" },
  ];

  console.log("-> Creating owners...");
  const insertedOwners = await db.insert(owners).values(ownersData).returning();

  const popPop = insertedOwners.find((o) => o.name === "PopPop")!;
  const mawMaw = insertedOwners.find((o) => o.name === "MawMaw")!;
  const emme = insertedOwners.find((o) => o.name === "Emme")!;

  // 2. Initial Notebook Definitions
  const notebooksData = [
    { title: "Music", ownerId: popPop.id },
    { title: "Defensive\nDriving", ownerId: popPop.id },
    { title: "Migraine", ownerId: mawMaw.id },
    { title: "Philosophy", ownerId: emme.id },
    { title: "Technology", ownerId: popPop.id },
    { title: "Recipes", ownerId: mawMaw.id },
  ];

  console.log("-> Creating notebooks...");
  const insertedNotebooks = await db
    .insert(notebooks)
    .values(notebooksData)
    .returning();

  // 3. Synthetic Source Metadata
  // We generate random 'createdAt' dates to verify sorting and UI date formatting
  const sourcesData = [];
  const now = new Date();

  console.log("-> Generating synthetic source metadata...");
  for (const nb of insertedNotebooks) {
    const numSources = Math.floor(Math.random() * 10) + 1;
    for (let i = 0; i < numSources; i++) {
      const randomDays = Math.floor(Math.random() * 30);
      const createdAt = new Date(
        now.getTime() - randomDays * 24 * 60 * 60 * 1000,
      );
      sourcesData.push({
        notebookId: nb.id,
        title: `Source ${i + 1}`,
        type: "text",
        content: "Sample content generated by seed script.",
        createdAt,
      });
    }
  }

  if (sourcesData.length > 0) {
    await db.insert(sources).values(sourcesData);
  }

  console.log("Seeding complete! Database is ready for local exploration.");
}

// Execute with standard error handling
seed().catch((err) => {
  console.error("Fatal Seeding Error:", err);
  process.exit(1);
});
