import { db } from "./src/db";
import { notebooks, owners, sources } from "./src/db/schema";

async function seed() {
  console.log("Seeding database...");
  
  // Create owners
  const ownersData = [
    { name: "PopPop" },
    { name: "MawMaw" },
    { name: "Emme" }
  ];
  
  const insertedOwners = await db.insert(owners).values(ownersData).returning();
  
  const popPop = insertedOwners.find(o => o.name === "PopPop")!;
  const mawMaw = insertedOwners.find(o => o.name === "MawMaw")!;
  const emme = insertedOwners.find(o => o.name === "Emme")!;

  // Create notebooks
  const notebooksData = [
    { title: "Music", ownerId: popPop.id },
    { title: "Defensive\nDriving", ownerId: popPop.id },
    { title: "Migraine", ownerId: mawMaw.id },
    { title: "Philosophy", ownerId: emme.id },
    { title: "Technology", ownerId: popPop.id },
    { title: "Recipes", ownerId: mawMaw.id },
  ];

  const insertedNotebooks = await db.insert(notebooks).values(notebooksData).returning();

  // Create some sources
  const sourcesData = [];
  const now = new Date();
  
  for (const nb of insertedNotebooks) {
    const numSources = Math.floor(Math.random() * 10) + 1;
    for (let i = 0; i < numSources; i++) {
        const randomDays = Math.floor(Math.random() * 30);
        const createdAt = new Date(now.getTime() - randomDays * 24 * 60 * 60 * 1000);
        sourcesData.push({
            notebookId: nb.id,
            title: `Source ${i+1}`,
            type: "text",
            content: "Sample content generated by seed",
            createdAt,
        });
    }
  }

  if (sourcesData.length > 0) {
      await db.insert(sources).values(sourcesData);
  }

  console.log("Seeding complete!");
}

seed().catch(console.error);
